const portfolioPieces = [
  {
    title: "Forage Collection 1",
    url: "/images/portfolio/TH2-bunny.png",
    width: "500",
    rows: "row-span-2",
    id: "1",
    key: 1,
  },
  {
    title: "Tundra Microsystems Web Design",
    url: "/images/portfolio/TMS-laptop.png",
    cols: "col-span-2",
    width: "600",
    id: "2",
    key: 2,
  },
  {
    title: "Tundra Microsystems",
    url: "/images/portfolio/TMS-card.png",
    cols: "col-span-2",
    width: "600",
    id: "3",
    key: 3,
  },
  {
    title: "Liquid Detergent Branding",
    url: "/images/portfolio/detergent.png",
    cols: "col-span-2",
    width: "600",
    id: "5",
    key: 5,
  },
  {
    title: "Forage Collection 2",
    url: "/images/portfolio/TH2-deer.png",
    width: "500",
    rows: "row-span-2",
    id: "4",
    key: 4,
  },
  {
    title: "Forage Collection 3",
    url: "/images/portfolio/TH2-lynx.png",
    width: "500",
    rows: "row-span-2",
    id: "6",
    key: 6,
  },
  {
    title: "How To Kill Your Plants",
    url: "/images/portfolio/HTKYP.jpg",
    cols: "col-span-2",
    width: "700",
    id: "6",
    key: 6,
    rows: "row-span-2",
  },
];

export default portfolioPieces;